# Nombre del Workflow
name: Build, Test and SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga tu código
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Instala las dependencias
      - name: Install Dependencies
        run: npm install

      # 3. EJECUTA LAS PRUEBAS y GENERA LA COBERTURA
      - name: Run Tests and Generate Coverage
        run: npm run test:unit -- --coverage

      # 4. (¡NUEVO PASO DE DEPURACIÓN!)
      #    Esto listará los archivos en la carpeta de cobertura
      - name: List Coverage Directory
        run: ls -R coverage

      # 5. Ejecuta el análisis de SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=ignaciov1
            -Dsonar.projectKey=Ignaciov1_AUY1102-Pipeline
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info